name: iOS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Set your project details here to avoid complex scripting
  PROJECT_NAME: "NightreignTimer.xcodeproj" # Or .xcworkspace if you use one
  SCHEME_NAME: "NightreignTimer" # Your primary scheme name

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ⬇️ THIS STEP IS NOW FIXED ⬇️
      - name: Select latest available iPhone simulator
        id: set_simulator
        run: |
          # Find the UUID of the last available iPhone simulator
          # This command is more robust and correctly extracts the UUID
          SIMULATOR_UUID=$(xcrun simctl list devices available | grep "iPhone" | tail -1 | grep -oE '[A-F0-9]{8}-([A-F0-9]{4}-){3}[A-F0-9]{12}')
          echo "device_id=$SIMULATOR_UUID" >> "$GITHUB_OUTPUT"
          echo "Selected simulator ID: $SIMULATOR_UUID"

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -scheme "$SCHEME_NAME" \
            -project "$PROJECT_NAME" \
            -destination "platform=iOS Simulator,id=${{ steps.set_simulator.outputs.device_id }}"

      - name: Test
        run: |
          xcodebuild test-without-building \
            -scheme "$SCHEME_NAME" \
            -project "$PROJECT_NAME" \
            -destination "platform=iOS Simulator,id=${{ steps.set_simulator.outputs.device_id }}"
